name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # https://github.com/ewwink/FsClock-Android/blob/master/.github/workflows/android.yml
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        name: Setup JDK 11
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: gradle
      - name: create dir
        run: mkdir -p app/build/outputs/apk/debug/
      - name: Set execution flag for gradlew
        run: chmod +x gradlew
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - uses: actions/upload-artifact@v4
        name: Upload APK
        with:
          name: apk
          path: app/build/outputs/apk/debug/fsclock.apk
